token: '5629725709:AAElI2-wZufSYgl2De-0Y3UJPdcA_DNDtQo'
url: https://www.cbr-xml-daily.ru/daily_json.js
#currency_name:
#  "RUB": Российский рубль,
#  "AUD": Австралийский доллар,
#  "AZN": Азербайджанский манат,
#  "GBP": Фунт стерлингов Соединенного королевства,
#  "AMD": Армянские драмы,
#  "BYN": Белорусский рубль,
#  "BGN": Болгарский лев,
#  "BRL": Бразильский реал,
#  "HUF": Венгерский форинт,
#  "HKD": Гонконгский доллар,
#  "DKK": Датская крона,
#  "USD": Доллар США,
#  "EUR": Евро,
#  "INR": Индийская рупия,
#  "KZT": Казахстанский тенге,
#  "CAD": Канадский доллар,
#  "KGS": Киргизский сом,
#  "CNY": Китайский юань,
#  "MDL": Молдавский лей,
#  "NOK": Норвежская крона,
#  "PLN": Польский злотый,
#  "RON": Румынский лей,
#  "XDR": СДР (специальные права заимствования),
#  "SGD": Сингапурский доллар,
#  "TJS": Таджикский сомони,
#  "TRY": Турецкая лира,
#  "TMT": Новый туркменский манат,
#  "UZS": Узбекский сум,
#  "UAH": Украинская гривна,
#  "CZK": Чешская крона,
#  "SEK": Шведская крона,
#  "CHF": Швейцарский франк,
#  "ZAR": Южноафриканских рэндов,
#  "KRW": Вон Республики Корея,
#  "JPY": Японских иен
